name: Build

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  windows-build:

    runs-on: windows-2022
    
    strategy:
      matrix:
        os-type: [windows-2022]
        openssl-version: [openssl-3.0.12]
        configuration: [VC-WIN64A]
        platform-toolset: [14.1, 14.2, 14.3]

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
    - name: Setup NASM
      uses: ilammy/setup-nasm@v1
    - name: Build
      shell: cmd
      run: |
        call "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Auxiliary\\Build\\vcvarsall.bat" x64 -vcvars_ver=${{ matrix.platform-toolset }}
        git clone https://github.com/openssl/openssl.git -b ${{ matrix.openssl-version }} --depth=1
        cd openssl
        perl Configure ${{ matrix.configuration }} no-zlib no-tests
        nmake
    - name: Package
      shell: cmd
      run: |
        mkdir package
        mkdir package\lib
        copy /Y openssl\libcrypto_static.lib package\lib\libcrypto_static.lib
        copy /Y openssl\libssl_static.lib package\lib\libssl_static.lib
        xcopy /I openssl\include\openssl package\include\openssl
        7z a -tzip windows-${{ matrix.openssl-version }}-${{ matrix.configuration }}-${{ matrix.platform-toolset }}.zip .\package\*
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: "*.zip"
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
